title: Laravel API tool kit
description: The Laravel API Toolkit is a comprehensive suite of tools designed to help you create robust, high-performance APIs using Laravel's industry-leading best practices. With this toolkit, you can streamline your development process and build APIs that are both fast and organized. Whether you're a seasoned developer or just getting started, the Laravel API Toolkit has everything you need to build world-class APIs that meet your business needs.
theme: just-the-docs
favicon_ico: "favicon.ico"
#logo: "https://raw.githubusercontent.com/ahmedesa/laravel-api-tool-kit/master/laravel-api-tool-kit.png"
//url: https://ahmedesa.github.io/laravel-api-tool-kit-docs
url: https://laravelapitoolkit.com

aux_links:
  Github Repository: https://github.com/ahmedesa/laravel-api-tool-kit

remote_theme: just-the-docs/just-the-docs

color_scheme: custom

plugins:
  - jekyll-seo-tag

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
